version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - brianlovin
  ignore:
  - dependency-name: algoliasearch
    versions:
    - 4.9.0
  - dependency-name: next
    versions:
    - 10.0.6
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
