// flow-typed signature: 65465d0c7093ee2f1fba25b9818328f2
// flow-typed version: <<STUB>>/bull_v3.4.8/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bull'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bull' {
  declare module.exports: any;
}
