// flow-typed signature: f32ca7615009e721fb59354dbb7f08bd
// flow-typed version: <<STUB>>/debug_v3.2.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'debug/karma.conf' {
  declare module.exports: any;
}

declare module 'debug/node' {
  declare module.exports: any;
}

declare module 'debug/src/browser' {
  declare module.exports: any;
}

declare module 'debug/src/debug' {
  declare module.exports: any;
}

declare module 'debug/src/index' {
  declare module.exports: any;
}

declare module 'debug/src/inspector-log' {
  declare module.exports: any;
}

declare module 'debug/src/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'debug/karma.conf.js' {
  declare module.exports: $Exports<'debug/karma.conf'>;
}
declare module 'debug/node.js' {
  declare module.exports: $Exports<'debug/node'>;
}
declare module 'debug/src/browser.js' {
  declare module.exports: $Exports<'debug/src/browser'>;
}
declare module 'debug/src/debug.js' {
  declare module.exports: $Exports<'debug/src/debug'>;
}
declare module 'debug/src/index.js' {
  declare module.exports: $Exports<'debug/src/index'>;
}
declare module 'debug/src/inspector-log.js' {
  declare module.exports: $Exports<'debug/src/inspector-log'>;
}
declare module 'debug/src/node.js' {
  declare module.exports: $Exports<'debug/src/node'>;
}
