// flow-typed signature: fcc16dd7fe47c9b8954b039abbe5cbbb
// flow-typed version: <<STUB>>/fathom-client_v1.0.0/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fathom-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fathom-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fathom-client/dist/fathom-client.cjs' {
  declare module.exports: any;
}

declare module 'fathom-client/dist/fathom-client.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fathom-client/dist/fathom-client.cjs.js' {
  declare module.exports: $Exports<'fathom-client/dist/fathom-client.cjs'>;
}
declare module 'fathom-client/dist/fathom-client.esm.js' {
  declare module.exports: $Exports<'fathom-client/dist/fathom-client.esm'>;
}
