// flow-typed signature: 7747590063c130adaf56f8eea75866e0
// flow-typed version: <<STUB>>/ioredis_v3.2.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ioredis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ioredis' {
  declare module.exports: any;
}
