// flow-typed signature: ecebc6419d3302881664ab35d1e765b8
// flow-typed version: <<STUB>>/micro-cors_v0.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-cors' {
  declare module.exports: any;
}
