// flow-typed signature: d25293179f7c2865f6813ac42f260bc0
// flow-typed version: <<STUB>>/micro-cacheable_v2.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-cacheable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-cacheable' {
  declare module.exports: any;
}
