// flow-typed signature: f75737a9d4726cb36cf16ac9495c0f63
// flow-typed version: <<STUB>>/now-env_v3.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'now-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'now-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'now-env/lib/apply-env' {
  declare module.exports: any;
}

declare module 'now-env/lib/get-value' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-now-json' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-pkg-json' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-required' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-secrets' {
  declare module.exports: any;
}

declare module 'now-env/lib/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'now-env/index' {
  declare module.exports: $Exports<'now-env'>;
}
declare module 'now-env/index.js' {
  declare module.exports: $Exports<'now-env'>;
}
declare module 'now-env/lib/apply-env.js' {
  declare module.exports: $Exports<'now-env/lib/apply-env'>;
}
declare module 'now-env/lib/get-value.js' {
  declare module.exports: $Exports<'now-env/lib/get-value'>;
}
declare module 'now-env/lib/load-now-json.js' {
  declare module.exports: $Exports<'now-env/lib/load-now-json'>;
}
declare module 'now-env/lib/load-pkg-json.js' {
  declare module.exports: $Exports<'now-env/lib/load-pkg-json'>;
}
declare module 'now-env/lib/load-required.js' {
  declare module.exports: $Exports<'now-env/lib/load-required'>;
}
declare module 'now-env/lib/load-secrets.js' {
  declare module.exports: $Exports<'now-env/lib/load-secrets'>;
}
declare module 'now-env/lib/module.js' {
  declare module.exports: $Exports<'now-env/lib/module'>;
}
