// flow-typed signature: c67ad28ed26ae168c8359dbb420c324c
// flow-typed version: <<STUB>>/react-instantsearch-dom_v5.3.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-instantsearch-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-instantsearch-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-instantsearch-dom/dist/cjs/components/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Highlighter' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Link' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/LinkList' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/List' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/PanelCallbackHandler' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Select' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/components/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/core/createInstantSearchServer' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/core/findResultsState' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/core/utils' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Index' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/InstantSearch' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/RangeSlider' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/cjs/widgets/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Highlighter' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Link' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/LinkList' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/List' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/PanelCallbackHandler' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Select' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/components/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/core/createInstantSearchServer' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/core/findResultsState' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/core/utils' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/ClearRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/CurrentRefinements' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/HierarchicalMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Highlight' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Hits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/HitsPerPage' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Index' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/InfiniteHits' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/InstantSearch' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Menu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/MenuSelect' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/NumericMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Pagination' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Panel' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/PoweredBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/RangeInput' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/RangeSlider' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/RatingMenu' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/RefinementList' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/SearchBox' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Snippet' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/SortBy' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/Stats' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/es/widgets/ToggleRefinement' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/umd/ReactInstantSearchDOM' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/dist/umd/ReactInstantSearchDOM.min' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch-dom/src/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-instantsearch-dom/dist/cjs/components/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Breadcrumb'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/ClearRefinements'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/CurrentRefinements'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/HierarchicalMenu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Highlight'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Highlighter.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Highlighter'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Hits'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/HitsPerPage'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/index.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/index'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/InfiniteHits'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Link.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Link'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/LinkList.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/LinkList'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/List.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/List'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Menu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/MenuSelect'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/NumericMenu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Pagination'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Panel'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/PanelCallbackHandler.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/PanelCallbackHandler'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/PoweredBy'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/RangeInput'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/RatingMenu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/RefinementList'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/ScrollTo'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/SearchBox'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Select.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Select'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Snippet'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/SortBy'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/Stats'>;
}
declare module 'react-instantsearch-dom/dist/cjs/components/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/components/ToggleRefinement'>;
}
declare module 'react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/core/createInstantSearchServer'>;
}
declare module 'react-instantsearch-dom/dist/cjs/core/findResultsState.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/core/findResultsState'>;
}
declare module 'react-instantsearch-dom/dist/cjs/core/utils.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/core/utils'>;
}
declare module 'react-instantsearch-dom/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/index'>;
}
declare module 'react-instantsearch-dom/dist/cjs/server.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/server'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Breadcrumb'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/ClearRefinements'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/CurrentRefinements'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/HierarchicalMenu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Highlight'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Hits'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/HitsPerPage'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Index.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Index'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/InfiniteHits'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/InstantSearch.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/InstantSearch'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Menu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/MenuSelect'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/NumericMenu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Pagination'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Panel'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/PoweredBy'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/RangeInput'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/RangeSlider.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/RangeSlider'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/RatingMenu'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/RefinementList'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/ScrollTo'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/SearchBox'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Snippet'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/SortBy'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/Stats'>;
}
declare module 'react-instantsearch-dom/dist/cjs/widgets/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/cjs/widgets/ToggleRefinement'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Breadcrumb'>;
}
declare module 'react-instantsearch-dom/dist/es/components/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/ClearRefinements'>;
}
declare module 'react-instantsearch-dom/dist/es/components/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/CurrentRefinements'>;
}
declare module 'react-instantsearch-dom/dist/es/components/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/HierarchicalMenu'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Highlight'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Highlighter.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Highlighter'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Hits'>;
}
declare module 'react-instantsearch-dom/dist/es/components/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/HitsPerPage'>;
}
declare module 'react-instantsearch-dom/dist/es/components/index.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/index'>;
}
declare module 'react-instantsearch-dom/dist/es/components/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/InfiniteHits'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Link.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Link'>;
}
declare module 'react-instantsearch-dom/dist/es/components/LinkList.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/LinkList'>;
}
declare module 'react-instantsearch-dom/dist/es/components/List.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/List'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Menu'>;
}
declare module 'react-instantsearch-dom/dist/es/components/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/MenuSelect'>;
}
declare module 'react-instantsearch-dom/dist/es/components/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/NumericMenu'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Pagination'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Panel'>;
}
declare module 'react-instantsearch-dom/dist/es/components/PanelCallbackHandler.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/PanelCallbackHandler'>;
}
declare module 'react-instantsearch-dom/dist/es/components/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/PoweredBy'>;
}
declare module 'react-instantsearch-dom/dist/es/components/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/RangeInput'>;
}
declare module 'react-instantsearch-dom/dist/es/components/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/RatingMenu'>;
}
declare module 'react-instantsearch-dom/dist/es/components/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/RefinementList'>;
}
declare module 'react-instantsearch-dom/dist/es/components/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/ScrollTo'>;
}
declare module 'react-instantsearch-dom/dist/es/components/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/SearchBox'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Select.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Select'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Snippet'>;
}
declare module 'react-instantsearch-dom/dist/es/components/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/SortBy'>;
}
declare module 'react-instantsearch-dom/dist/es/components/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/Stats'>;
}
declare module 'react-instantsearch-dom/dist/es/components/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/components/ToggleRefinement'>;
}
declare module 'react-instantsearch-dom/dist/es/core/createInstantSearchServer.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/core/createInstantSearchServer'>;
}
declare module 'react-instantsearch-dom/dist/es/core/findResultsState.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/core/findResultsState'>;
}
declare module 'react-instantsearch-dom/dist/es/core/utils.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/core/utils'>;
}
declare module 'react-instantsearch-dom/dist/es/index.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/index'>;
}
declare module 'react-instantsearch-dom/dist/es/server.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/server'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Breadcrumb.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Breadcrumb'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/ClearRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/ClearRefinements'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/CurrentRefinements.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/CurrentRefinements'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/HierarchicalMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/HierarchicalMenu'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Highlight.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Highlight'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Hits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Hits'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/HitsPerPage.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/HitsPerPage'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Index.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Index'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/InfiniteHits.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/InfiniteHits'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/InstantSearch.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/InstantSearch'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Menu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Menu'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/MenuSelect.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/MenuSelect'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/NumericMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/NumericMenu'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Pagination.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Pagination'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Panel.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Panel'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/PoweredBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/PoweredBy'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/RangeInput.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/RangeInput'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/RangeSlider.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/RangeSlider'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/RatingMenu.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/RatingMenu'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/RefinementList.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/RefinementList'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/ScrollTo.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/ScrollTo'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/SearchBox.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/SearchBox'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Snippet.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Snippet'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/SortBy.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/SortBy'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/Stats.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/Stats'>;
}
declare module 'react-instantsearch-dom/dist/es/widgets/ToggleRefinement.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/es/widgets/ToggleRefinement'>;
}
declare module 'react-instantsearch-dom/dist/umd/ReactInstantSearchDOM.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/umd/ReactInstantSearchDOM'>;
}
declare module 'react-instantsearch-dom/dist/umd/ReactInstantSearchDOM.min.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/dist/umd/ReactInstantSearchDOM.min'>;
}
declare module 'react-instantsearch-dom/server.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/server'>;
}
declare module 'react-instantsearch-dom/src/server.js' {
  declare module.exports: $Exports<'react-instantsearch-dom/src/server'>;
}
