// flow-typed signature: 818da6437e31807969bc2d9d3765e18e
// flow-typed version: <<STUB>>/react-instantsearch_v5.3.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-instantsearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-instantsearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-instantsearch/connectors' {
  declare module.exports: any;
}

declare module 'react-instantsearch/dom' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/connectors' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/dom' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/index' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/native' {
  declare module.exports: any;
}

declare module 'react-instantsearch/es/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch/native' {
  declare module.exports: any;
}

declare module 'react-instantsearch/server' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Connectors' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Connectors.min' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Core' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Core.min' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Dom' {
  declare module.exports: any;
}

declare module 'react-instantsearch/umd/Dom.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-instantsearch/connectors.js' {
  declare module.exports: $Exports<'react-instantsearch/connectors'>;
}
declare module 'react-instantsearch/dom.js' {
  declare module.exports: $Exports<'react-instantsearch/dom'>;
}
declare module 'react-instantsearch/es/connectors.js' {
  declare module.exports: $Exports<'react-instantsearch/es/connectors'>;
}
declare module 'react-instantsearch/es/dom.js' {
  declare module.exports: $Exports<'react-instantsearch/es/dom'>;
}
declare module 'react-instantsearch/es/index.js' {
  declare module.exports: $Exports<'react-instantsearch/es/index'>;
}
declare module 'react-instantsearch/es/native.js' {
  declare module.exports: $Exports<'react-instantsearch/es/native'>;
}
declare module 'react-instantsearch/es/server.js' {
  declare module.exports: $Exports<'react-instantsearch/es/server'>;
}
declare module 'react-instantsearch/index' {
  declare module.exports: $Exports<'react-instantsearch'>;
}
declare module 'react-instantsearch/index.js' {
  declare module.exports: $Exports<'react-instantsearch'>;
}
declare module 'react-instantsearch/native.js' {
  declare module.exports: $Exports<'react-instantsearch/native'>;
}
declare module 'react-instantsearch/server.js' {
  declare module.exports: $Exports<'react-instantsearch/server'>;
}
declare module 'react-instantsearch/umd/Connectors.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Connectors'>;
}
declare module 'react-instantsearch/umd/Connectors.min.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Connectors.min'>;
}
declare module 'react-instantsearch/umd/Core.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Core'>;
}
declare module 'react-instantsearch/umd/Core.min.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Core.min'>;
}
declare module 'react-instantsearch/umd/Dom.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Dom'>;
}
declare module 'react-instantsearch/umd/Dom.min.js' {
  declare module.exports: $Exports<'react-instantsearch/umd/Dom.min'>;
}
