// flow-typed signature: 4a4ba40d4acce08ec79fef6e453a3db8
// flow-typed version: <<STUB>>/remove-markdown_v0.3.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-markdown' {
  declare module.exports: any;
}
