// flow-typed signature: eb1bd42de2169c08e8228fb94c361daa
// flow-typed version: <<STUB>>/stopword_v0.1.13/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stopword'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stopword' {
  declare module.exports: any;
}
