// @flow
import hosts from './hosts'

export default [
  {
    id: 363,
    name: "Developer Tea",
    slug: "developer-tea",
    description: "A podcast for developers designed to fit inside your tea break",
    simplecastId: 363,
    artworkUrl: "https://media.simplecast.com/podcast/image/363/small_1471485029-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id955596067",
    overcastUrl: "https://overcast.fm/itunes955596067",
    pocketCastsUrl: "http://pca.st/itunes/955596067",
    rssFeedUrl: "http://feeds.feedburner.com/developertea",
    googlePodcastsUrl: "https://play.google.com/music/m/Isv2vlzebfo5xid4zolzxpqber4?t=Developer_Tea",
    castroUrl: "https://castro.fm/itunes/955596067",
    breakerUrl: "https://www.breaker.audio/developer-tea",
    applePodcastId: "955596067",
    twitterUsername: "developertea",
    hosts: [hosts.jcutrell]
  },

  {
    id: 1034,
    name: "Design Details",
    slug: "design-details",
    description: "A weekly conversation about design process and culture",
    simplecastId: 1034,
    artworkUrl: "https://media.simplecast.com/podcast/image/1034/small_1471485006-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id947191070",
    overcastUrl: "https://overcast.fm/itunes947191070",
    pocketCastsUrl: "http://pca.st/itunes/947191070",
    rssFeedUrl: "http://simplecast.fm/podcasts/1034/rss",
    googlePodcastsUrl: "https://play.google.com/music/m/Iyvjpq3k44ux2azsmvlxe3cc5by?t=Design_Details",
    castroUrl: "https://castro.fm/itunes/947191070",
    breakerUrl: "https://www.breaker.audio/design-details",
    applePodcastId: "947191070",
    twitterUsername: "designdetailsfm",
    hosts: [hosts.marshallbock, hosts.brian_lovin]
  },

  {
    id: 1332,
    name: "Immutable",
    slug: "immutable",
    description: "A short, weekly show about design and development",
    simplecastId: 1332,
    artworkUrl: "https://media.simplecast.com/podcast/image/1332/small_1471485110-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1035147995",
    overcastUrl: "https://overcast.fm/itunes1035147995",
    pocketCastsUrl: "http://pca.st/itunes/1035147995",
    rssFeedUrl: "http://simplecast.fm/podcasts/1332/rss",
    googlePodcastsUrl: "https://play.google.com/music/m/Ibpdxh2uj5dd6gh5aoim6vscp5e?t=Immutable",
    castroUrl: "https://castro.fm/itunes/1035147995",
    breakerUrl: "https://www.breaker.audio/immutable",
    applePodcastId: "1035147995",
    twitterUsername: "ImmutableFM",
    hosts: [hosts.soffes, hosts.defaultbryn]
  },

  {
    id: 1386,
    name: "Does Not Compute",
    slug: "does-not-compute",
    description: "A weekly chat about the lives and workflows of modern web developers",
    simplecastId: 1386,
    artworkUrl: "https://media.simplecast.com/podcast/image/1386/small_1474491978-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1048731980",
    overcastUrl: "https://overcast.fm/itunes1048731980",
    pocketCastsUrl: "http://pca.st/itunes/1048731980",
    rssFeedUrl: "http://simplecast.fm/podcasts/1386/rss",
    googlePodcastsUrl: "https://spec.fm/podcasts/does-not-compute",
    castroUrl: "https://castro.fm/itunes/1048731980",
    breakerUrl: "https://www.breaker.audio/does-not-compute",
    applePodcastId: "1048731980",
    twitterUsername: "dnccast",
    hosts: [hosts.seanwashbot, hosts.schrockwell]
  },

  {
    id: 1457,
    name: "Vicarious",
    slug: "vicarious",
    description: "Everyday escapism from a designers' point of view.",
    simplecastId: 1457,
    artworkUrl: "https://media.simplecast.com/podcast/image/1457/small_1458002335-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1055180013",
    overcastUrl: "https://overcast.fm/itunes1055180013",
    pocketCastsUrl: "http://pca.st/itunes/1055180013",
    rssFeedUrl: "http://simplecast.fm/podcasts/1457/rss",
    googlePodcastsUrl: "https://spec.fm/podcasts/vicarious",
    castroUrl: "https://castro.fm/itunes/1055180013",
    breakerUrl: "https://www.breaker.audio/vicarious",
    applePodcastId: "1055180013",
    twitterUsername: "vicarious_fm",
    hosts: [hosts.defaultbryn, hosts.marshallbock, hosts.sortino, hosts.sarahberus]
  },

  {
    id: 1684,
    name: "Fragmented",
    slug: "fragmented",
    description: "An Android developer podcast where we talk about building good software and becoming better Android developers",
    simplecastId: 1684,
    artworkUrl: "https://media.simplecast.com/podcast/image/1684/small_1474255312-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id968779958",
    overcastUrl: "https://overcast.fm/itunes968779958",
    pocketCastsUrl: "http://pca.st/itunes/968779958",
    rssFeedUrl: "http://simplecast.com/podcasts/1684/rss",
    googlePodcastsUrl: "https://play.google.com/music/m/Ipvgdmgnkk44rvdvdyg22lql4sq?t=Fragmented_-_Android_Developer_Podcast",
    castroUrl: "https://castro.fm/itunes/968779958",
    breakerUrl: "https://www.breaker.audio/fragmented-android-developer-podcast",
    applePodcastId: "968779958",
    twitterUsername: "FragmentedCast",
    hosts: [hosts.donnfelker, hosts.kaushikgopal]
  },

  {
    id: 2070,
    name: "Runtime",
    slug: "runtime",
    description: "Sam Soffes and Caleb Davenport talk about Swift, iOS, and other things they like",
    simplecastId: 2070,
    artworkUrl: "https://media.simplecast.com/podcast/image/2070/small_1471485227-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1122203945",
    overcastUrl: "https://overcast.fm/itunes1122203945",
    pocketCastsUrl: "http://pca.st/itunes/1122203945",
    rssFeedUrl: "http://simplecast.com/podcasts/2070/rss",
    googlePodcastsUrl: "",
    castroUrl: "https://castro.fm/itunes/1122203945",
    breakerUrl: "https://www.breaker.audio/runtime",
    applePodcastId: "1122203945",
    twitterUsername: "runtimefm",
    hosts: [hosts.soffes, hosts.calebd]
  },

  {
    id: 2128,
    name: "Orthogonal",
    slug: "orthogonal",
    description: "A show about finance, freelance and being better at both",
    simplecastId: 2128,
    artworkUrl: "https://media.simplecast.com/podcast/image/2128/small_1471485142-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1131320952",
    overcastUrl: "https://overcast.fm/itunes1131320952",
    pocketCastsUrl: "http://pca.st/itunes/1131320952",
    rssFeedUrl: "http://simplecast.com/podcasts/2128/rss",
    googlePodcastsUrl: "",
    castroUrl: "https://castro.fm/itunes/1131320952",
    breakerUrl: "https://www.breaker.audio/orthogonal",
    applePodcastId: "1131320952",
    twitterUsername: "getorthogonal",
    hosts: [hosts.cfoandrew, hosts.mrbrettkelly]
  },

  {
    id: 2693,
    name: "Swift Unwrapped",
    slug: "swift-unwrapped",
    description: "A 30-minute spin off of Swift Weekly Brief and other Swifty news.",
    simplecastId: 2693,
    artworkUrl: "https://media.simplecast.com/podcast/image/2693/small_1488855184-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1209817203",
    overcastUrl: "https://overcast.fm/itunes1209817203",
    pocketCastsUrl: "http://pca.st/itunes/1209817203",
    rssFeedUrl: "https://simplecast.com/podcasts/2693/rss",
    googlePodcastsUrl: "",
    castroUrl: "https://castro.fm/itunes/1209817203",
    breakerUrl: "https://www.breaker.audio/swift-unwrapped",
    applePodcastId: "1209817203",
    twitterUsername: null,
    hosts: [hosts.simjp, hosts.jesse_squires]
  },

  {
    id: 4211,
    name: "Toolsday",
    slug: "toolsday",
    description: "A show about the latest in tech tools, tips, and tricks on Tuesdays at 2",
    simplecastId: 4211,
    artworkUrl: "https://media.simplecast.com/podcast/image/4211/small_1516237529-artwork.jpg",
    iTunesUrl: "https://geo.itunes.apple.com/ca/podcast/feed/id1063765302",
    overcastUrl: "https://overcast.fm/itunes1063765302",
    pocketCastsUrl: "http://pca.st/itunes/1063765302",
    rssFeedUrl: "https://rss.simplecast.com/podcasts/4211/rss",
    googlePodcastsUrl: "",
    castroUrl: "https://castro.fm/itunes/1063765302",
    breakerUrl: "https://www.breaker.audio/toolsday",
    applePodcastId: "1063765302",
    twitterUsername: "toolsday",
    hosts: [hosts.una, hosts.chrisdhanaraj]
  }
]